#!/bin/bash
avr-gcc -g -mmcu=attiny13 -o DroneEyes.elf DroneEyes.o
avr-objcopy -j .text -j .data -O ihex DroneEyes.elf DroneEyes.hex
avrdude -p t13 -P usb -c avrispmkii -b 125000 -U lfuse:w:0x79:m -U hfuse:w:0xff:m
avrdude -p t13 -P usb -c avrispmkii -b 125000 -U flash:w:DroneEyes.hex 
